In [1]:
import pandas as pd

In [3]:
recipe_w_ratings_df = pd.read_csv("input_stage2/recipe_user_ratings.csv")
recipe_wo_ratings_old_df = pd.read_csv("input_stage2/price_mapped_nutrients.csv")

In [4]:
recipe_w_ratings_df

,recipe_id,name,calories (g),total fat (g),sugar (g),sodium (g),protein (g),saturated fat (g),carbohydrates (g),ingredients,user_id,rating
0,137739,arriba baked winter squash mexican style,103000.0,0.0,650.0,0.0,100.0,0.0,1200.0,"['winter squash', 'mexican seasoning', 'mixed ...",4470,5
1,137739,arriba baked winter squash mexican style,103000.0,0.0,650.0,0.0,100.0,0.0,1200.0,"['winter squash', 'mexican seasoning', 'mixed ...",593927,5
2,137739,arriba baked winter squash mexican style,103000.0,0.0,650.0,0.0,100.0,0.0,1200.0,"['winter squash', 'mexican seasoning', 'mixed ...",178427,5
3,31490,a bit different breakfast pizza,346800.0,1170.0,0.0,40800.0,1100.0,700.0,300.0,"['prepared pizza crust', 'sausage patty', 'egg...",319943,4
4,31490,a bit different breakfast pizza,346800.0,1170.0,0.0,40800.0,1100.0,700.0,300.0,"['prepared pizza crust', 'sausage patty', 'egg...",674022,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1132362,308080,zydeco ya ya deviled eggs,118400.0,390.0,100.0,7200.0,300.0,100.0,0.0,"['hard-cooked eggs', 'mayonnaise', 'dijon must...",28177,5
1132363,298512,cookies by design cookies on a stick,376000.0,715.0,2850.0,26400.0,350.0,420.0,2700.0,"['butter', 'eagle brand condensed milk', 'ligh...",804234,1
1132364,298509,cookies by design sugar shortbread cookies,349800.0,910.0,1650.0,9600.0,200.0,220.0,1800.0,"['granulated sugar', 'shortening', 'eggs', 'fl...",866651,1
1132365,298509,cookies by design sugar shortbread cookies,349800.0,910.0,1650.0,9600.0,200.0,220.0,1800.0,"['granulated sugar', 'shortening', 'eggs', 'fl...",1546277,5
1132366,298509,cookies by design sugar shortbread cookies,349800.0,910.0,1650.0,9600.0,200.0,220.0,1800.0,"['granulated sugar', 'shortening', 'eggs', 'fl...",1803287907,0

In [5]:
recipe_wo_ratings_old_df

,fdc_id,description,product,item_prices,unpriced_items,priced_items,total_items,priced_share,adj,verb,total_price,protein_g,fat_g,carb_g,energy_kcal,fiber_g,sodium_mg,cholesterol_mg,satfat_g,sugars_g
0,167512,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...","['layer buttermilk biscuits', 'dough']",{'layer buttermilk biscuits': 4.5},['dough'],1,2,0.5,"['Golden', 'Artificial']",['refrigerated'],0.00,5.88,13.2400,41.1800,307.0,1.2,1059.0,0.00,2.9410,5.88
1,167516,"Waffles, buttermilk, frozen, ready-to-heat",['waffles'],{'waffles': 6.85},[],1,1,1.0,['ready'],['frozen'],6.85,6.58,9.2200,41.0500,273.0,2.2,621.0,15.00,1.8980,4.30
2,167517,"Waffle, buttermilk, frozen, ready-to-heat, toa...",['waffle'],{'waffle': 6.85},[],1,1,1.0,['ready'],"['frozen', 'toasted']",6.85,7.42,9.4900,48.3900,309.0,2.6,710.0,13.00,2.2750,4.41
3,167518,"Waffle, buttermilk, frozen, ready-to-heat, mic...",['waffle'],{'waffle': 6.85},[],1,1,1.0,['ready'],"['frozen', 'microwaved']",6.85,6.92,9.4000,44.1600,289.0,2.4,663.0,16.00,2.0570,4.50
4,167519,"Waffle, plain, frozen, ready-to-heat, microwave",['waffle'],{'waffle': 6.85},[],1,1,1.0,"['plain', 'ready']",['frozen'],6.85,6.71,9.9100,45.4100,298.0,2.4,682.0,16.00,1.5800,5.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10840,2710811,Vegetables as ingredient in soups,"['vegetables', 'soups']","{'vegetables': 3.52, 'soups': 4.59}",[],2,2,1.0,[],[],8.11,1.87,0.3300,10.5600,50.0,2.0,15.0,0.00,0.0500,2.34
10841,2710812,Vegetables as ingredient in stews,"['vegetables', 'stews']",{'vegetables': 3.52},['stews'],1,2,0.5,[],[],0.00,1.77,0.3000,12.6700,59.0,2.6,34.0,0.00,0.0400,3.16
10842,2710813,Sauce as ingredient in hamburgers,['sauce'],{'sauce': 3.95},[],1,1,1.0,[],[],3.95,1.34,22.8500,17.1400,272.0,0.6,845.0,13.00,3.5440,13.08
10843,2710814,Industrial oil as ingredient in food,['oil'],{'oil': 8.85},[],1,1,1.0,['Industrial'],[],8.85,0.00,100.0000,0.0000,892.0,0.0,0.0,0.00,32.6720,0.00
10844,2768188,"Alaska Pollock, raw",['alaska pollock'],{'alaska pollock': 8.95},[],1,1,1.0,['raw'],[],8.95,17.33,0.9925,0.0565,NaN,0.0,114.8,59.95,0.2374,NaN